### ISSUE TITLE
和原Android ButterKnife Zelezny 有同样的Bug

### ISSUE THREAD

**Issue by lydlovexyz** [ParfoisMeng/Android-ButterKnife-Injections#6]
有时候不能正常生成代码...

**Comment by lydlovexyz** [comment]
<img width="591" alt="微信截图_20190918112255" src="https://user-images.githubusercontent.com/19246347/65105194-b900b100-da06-11e9-98ac-32bf2270b55b.png">

**Comment by lydlovexyz** [comment]
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.avast.android.butterknifezelezny.model.Element.getFieldName(Element.java:125)
	at com.avast.android.butterknifezelezny.model.Element.<init>(Element.java:44)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:206)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1040)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1040)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:96)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:730)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:55)
	at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
	at com.avast.android.butterknifezelezny.common.Utils.getIDsFromLayout(Utils.java:164)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:181)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1040)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
	at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1040)
	at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:81)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
	at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
	at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:96)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:730)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
	at com.avast.android.butterknifezelezny.common.Utils$1.visitElement(Utils.java:168)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:55)
	at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
	at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
	at com.avast.android.butterknifezelezny.common.Utils.getIDsFromLayout(Utils.java:164)
	at com.avast.android.butterknifezelezny.common.Utils.getIDsFromLayout(Utils.java:154)
	at com.avast.android.butterknifezelezny.InjectAction.actionPerformedImpl(InjectAction.java:73)
	at com.avast.android.butterknifezelezny.InjectAction.actionPerformed(InjectAction.java:58)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:153)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:249)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:200)
	at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:190)
	at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:184)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$12(AbstractPopup.java:1417)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3049)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:178)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:130)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1413)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:308)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:279)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:138)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:193)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:107)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:157)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:444)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:397)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:338)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:251)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:114)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:150)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:86)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ParfoisMeng** [comment]
昨天想修改点东西来着，奈何IDEA插件开发的东西升级了，捣鼓了半天没升级成，最后都放弃了。。。
没想到今天又收到issues。。。
短期内真的解决不了了，国内相关资料略少，国外的又看得懵懵懂懂。。。我现在连项目都加不进IDEA，当初不该删本地的。。。

话说老哥不考虑用Kotlin吗？kotlinx直接引用xml里的ID炒鸡好用啊。。。（Kotlin与Java兼容，项目里混着用完全没问题）

**Comment by lydlovexyz** [comment]
换了好几个版本的AS都不行
从最新的3.5.0然后回退到3.4.2到回退到3.3.2,都不能用,好奇葩呀.
AS插件这么坑的吗???
KT还没在项目里边使用呀.
哈哈哈哈

**Comment by lydlovexyz** [comment]
换了几个同款的ButterKnife插件,也是一样的问题,貌似大家都是基于Android ButterKnife Zelezny改的吧.
没问题都没问题,有问题大家都不能用.
好尴尬呀....

**Comment by ParfoisMeng** [comment]
我这里是没遇到过这个问题。。。

**Comment by lydlovexyz** [comment]
问题不大

**Comment by lydlovexyz** [comment]
感谢
